Repository Tada-Project/tada, pull requests merged in 2019-04, with the labels that each got.

#33 Program Improvement: Update Help Display
  .DS_Store
  tada/.DS_Store
  tada/util/arguments.py
  tada/util/display.py
Labels: documentation, feature

#32 Added new function to generate: String
  tada/util/generate.py
  tests/test_generate.py
Labels: feature

#35 Documentation Improvement: Update README
  .DS_Store
  README.md
  tada/.DS_Store
Labels: documentation

#36 Created a results table and analysis function
  .travis.yml
  tada/util/constants.py
  tada/util/results.py
  tada_a_bigoh.py
  tests/test_results.py
Labels: feature, in-progress

#39 Analysis Function, Indicator, Backfill, and Generate Random Input List
  tada/util/generate.py
  tada_a_bigoh.py
  tests/test_generate.py
Labels: bug, feature
